name: Generate Branches File

on:
  workflow_dispatch:
    inputs:
      repo:
        description: '选择源码'
        required: true
        default: 'lede'
        type: choice
        options:
          - 'lede'
          - 'immortalwrt'
          - 'immortalwrt-mt798x'

jobs:
  generate-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Set repository info
        id: set_repo_info
        run: |
          case "${{ github.event.inputs.repo }}" in
            lede)
              echo "REPO_OWNER=coolsnowwolf" >> $GITHUB_ENV
              echo "REPO_NAME=lede" >> $GITHUB_ENV
              ;;
            immortalwrt)
              echo "REPO_OWNER=immortalwrt" >> $GITHUB_ENV
              echo "REPO_NAME=immortalwrt" >> $GITHUB_ENV
              ;;
            immortalwrt-mt798x)
              echo "REPO_OWNER=padavanonly" >> $GITHUB_ENV
              echo "REPO_NAME=immortalwrt-mt798x" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid repository selected" >&2
              exit 1
              ;;
          esac

      - name: Debug info
        run: |
          echo "REPO_OWNER=${{ env.REPO_OWNER }}"
          echo "REPO_NAME=${{ env.REPO_NAME }}"

      - name: Get branches from another repository
        run: |
          # 使用 PAT 访问另一个仓库并获取分支
          branches=$(git ls-remote --heads https://x-access-token:${{ secrets.HQ_TOKEN }}@github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}.git | awk '{print $2}' | sed 's|refs/heads/||' | tr '\n' ',' | sed 's/,$//')
          echo "Branches: $branches" > branches.txt

      - name: Display branches
        run: cat branches.txt
